Repository AY2223S1-CS2103T-T09-1/tp, pull requests merged in 2022-10, with the labels that each got.

#95 Add new user stories in DeveloperGuide.md
  docs/DeveloperGuide.md
Labels: priority.High, type.Story, type.Task

#120 Remove Email.java and Phone.java from company
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/company/Email.java
  src/main/java/seedu/address/model/company/Phone.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/company/EmailTest.java
  src/test/java/seedu/address/model/company/PhoneTest.java
Labels: type.Task

#146 Update Create and Add Feature in UG
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/CreateCommand.java
Labels: priority.High, type.Task

#151 Transaction Commands: prevent commands from changing the list state
  src/main/java/seedu/address/logic/commands/BuyCommand.java
  src/main/java/seedu/address/logic/commands/SellCommand.java
Labels: priority.Medium, type.Bug
